Repository Care-Amarillo/Care-Amarillo-Backend, pull requests merged in 2020-10, with the labels that each got.

#30 update readme to have new lines and link frontend code
  README.md
Labels: hacktoberfest

#32 fix idToSearch Bug in auditEntry
  auditEntry.js
Labels: bug, hacktoberfest

#33 fix auth check on managing user by id
  index.js
Labels: bug, hacktoberfest

#34 change create provider to work without passing an user id
  index.js
Labels: hacktoberfest

#36 create user and make managing provider id
  index.js
Labels: enhancement, hacktoberfest

#42 connect services; fix get managing user by user id bug;
  README.md
  addUser.js
  index.js
  provider.js
Labels: hacktoberfest
